FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y wireguard iproute2 iptables curl sudo && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /opt/wireguard-manager

WORKDIR /opt/wireguard-manager

RUN chmod +x ./wireguard-manager.sh

EXPOSE 51820/udp

ENTRYPOINT ["./wireguard-manager.sh"]
